#################################################
#                 TPM PLUGINS                   #
#################################################

# Plugin Manager (required)
set -g @plugin 'tmux-plugins/tpm'

########################
# Theme
########################

set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'catppuccin'
# set -g @tmux2k-icons-only true
set -g @tmux2k-git-display-status 'true'
set -g @tmux2k-time-format '%a %Y-%m-%d %H:%M'
set -g @tmux2k-right-plugins "time"
set -g @tmux2k-left-plugins "git"

########################
# Session Persistence
########################

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

########################
# Optional Plugins
########################

# Floating panes
# set -g @plugin 'omerxx/tmux-floax'
# set -g @floax-bind '-n M-p'
# set -g @floax-bind-menu 'P'
# set -g @floax-width '80%'
# set -g @floax-height '80%'
# set -g @floax-border-color 'magenta'


#################################################
#               TPM INITIALIZATION              #
#################################################

# MUST be last line — do not place anything after this
run '~/.config/tmux/plugins/tpm/tpm'
