source-file ~/.config/tmux/tmux-base.conf
source-file ~/.config/tmux/tmux-theme.conf
source-file ~/.config/tmux/tmux-status.conf

# Popup session toggle
bind -n M-m if-shell -F '#{==:#{session_name},popup}' { detach-client } {
    display-popup -E -xC -yC -w80% -h80% 'tmux attach -t popup || tmux new -s popup'
}

# OpenCode popup session toggle (-C closes the current popup instead of re-running it)
bind -n M-o display-popup -E -xC -yC -w80% -h80% 'env -u TMUX tmux -L opencode-popup -f ~/.config/tmux/opencode-tmux.conf new-session -A -s opencode-popup opencode'

bind -n M-u if-shell -F '#{==:#{session_name},opencode-popup}' { detach-client } {
    display-popup -E -xC -yC -w80% -h80% 'tmux attach -t opencode-popup || env -u TMUX tmux -L opencode-popup -f ~/.config/tmux/opencode-tmux.conf new-session -A -s opencode-popup opencode'
}

# Quick note popup
bind -n M-N display-popup -E "nvim ~/notes/quick-note.md"



if-shell "test -r ~/.config/tmux/tmux-plugins.conf" "source-file ~/.config/tmux/tmux-plugins.conf"
