source-file ~/.config/tmux/tmux-base.conf

# Popup session toggle
bind -n M-m if-shell -F '#{==:#{session_name},popup}' { detach-client } {
    display-popup -E -xC -yC -w80% -h80% 'tmux attach -t popup || tmux new -s popup'
}

# OpenCode popup session toggle
bind -n M-o display-popup -E -xC -yC -w80% -h80% 'env -u TMUX tmux -L opencode-popup -f ~/.config/tmux/opencode-tmux.conf new-session -A -s opencode-popup opencode'

# Quick note popup
bind -n M-N display-popup -E "nvim ~/notes/quick-note.md"



source-file ~/.config/tmux/tmux-plugins.conf
