# Native sharp-tab status line.

set -g status on
set -g status-position top
set -g status-interval 5
set -g status-justify absolute-centre

set -gF status-style "fg=#{@theme_bar_fg},bg=#{@theme_bar_bg}"
set -gF message-style "fg=#{@theme_message_fg},bg=#{@theme_message_bg}"
set -gF message-command-style "fg=#{@theme_message_fg},bg=#{@theme_message_bg}"
set -gF pane-border-style "fg=#{@theme_pane_border}"
set -gF pane-active-border-style "fg=#{@theme_pane_active_border}"
set -gF display-panes-colour "#{@theme_display_pane}"
set -gF display-panes-active-colour "#{@theme_display_pane_active}"

set -g status-left-length 80
set -g status-right-length 80
set -g window-status-separator " "


# Other separators:  ,  ,
# Triangle left: \ue0b2, Right: \ue0b0
set -g @left_separator ""
set -g @right_separator ""


set -g status-left '#[fg=#{@theme_session_fg},bg=#{@theme_session_bg}] #S #[fg=#{@theme_session_bg},bg=#{@theme_bar_bg}]#{@right_separator}#(/home/jimmy/.config/tmux/status-git.sh #{q:pane_current_path})'

set -g status-right '#[fg=#{@theme_time_bg},bg=#{@theme_bar_bg}]#{@left_separator}#[fg=#{@theme_time_fg},bg=#{@theme_time_bg}] %a %Y-%m-%d %H:%M '

setw -g window-status-format '#[fg=#{@theme_window_bg},bg=#{@theme_bar_bg}]#{@left_separator}#[fg=#{@theme_window_fg},bg=#{@theme_window_bg}] #I #W #[fg=#{@theme_window_bg},bg=#{@theme_bar_bg}]#{@right_separator}'
setw -g window-status-current-format '#[fg=#{@theme_window_active_bg},bg=#{@theme_window_active_fg}]#{@left_separator}#[fg=#{@theme_window_active_fg},bg=#{@theme_window_active_bg},bold] #I #W #[fg=#{@theme_window_active_bg},bg=#{@theme_window_active_fg}]#{@right_separator}'

setw -g window-status-activity-style 'none'
setw -g window-status-bell-style 'bold'
setw -g window-status-last-style 'none'
