#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "dotfiles"
path = "~/.config/"
startup_command = "bash ~/.config/sesh/start-dotfiles-session.sh"
preview_command = "bash ~/.config/sesh/preview-dotfiles.sh"
