splash = false

wallpaper {
    monitor = desc:ASUSTek COMPUTER INC VG27AQ1A LALMQS099884
    path = /home/jimmy/Pictures/wallpapers/wallhaven-Mountains_1440x2560.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:ASUSTek COMPUTER INC VG27B L2LMQS041890
    path = /home/jimmy/Pictures/wallpapers/wallhaven-Cat_by_water_2560x1440.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:ASUSTek COMPUTER INC VG27B K7LMQS089435
    path = /home/jimmy/Pictures/wallpapers/wallhaven-Space_galaxy_2560x1440.png
    fit_mode = cover
}
