set -g @theme_bar_bg '#1e2030'
set -g @theme_bar_fg '#cad3f5'

set -g @theme_message_bg '#8aadf4'
set -g @theme_message_fg '#1e2030'

set -g @theme_pane_border '#6e738d'
set -g @theme_pane_active_border '#8aadf4'
set -g @theme_display_pane '#8aadf4'
set -g @theme_display_pane_active '#f5a97f'

set -g @theme_session_bg '#8aadf4'
set -g @theme_session_fg '#1e2030'

set -g @theme_git_bg '#a6da95'
set -g @theme_git_fg '#1e2030'

set -g @theme_time_bg '#eed49f'
set -g @theme_time_fg '#1e2030'

set -g @theme_window_bg '#363a4f'
set -g @theme_window_fg '#cad3f5'
set -g @theme_window_active_bg '#8aadf4'
set -g @theme_window_active_fg '#1e2030'
